export const API_BASE =
  (typeof window !== 'undefined' ? (process.env.NEXT_PUBLIC_API_URL ?? '') : process.env.NEXT_PUBLIC_API_URL) ||
  'http://localhost:4000/api';

export const THEME = {
  primary: '#135bec',
  backgroundLight: '#f6f6f8',
  backgroundDark: '#101622',
  surfaceLight: '#ffffff',
  surfaceDark: '#1e293b',
  inputBg: '#f8f9fc',
  inputBorder: '#cfd7e7',
  textMain: '#0d121b',
  textSub: '#4c669a',
} as const;

export const ROLE_TO_DASHBOARD: Record<string, string> = {
  super_admin: '/dashboard/super-admin',
  admin: '/dashboard/admin',
  cr: '/dashboard/cr',
  moderator: '/dashboard/moderator',
  student: '/dashboard/member',
};

export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  admin: '/dashboard/admin',
  superAdmin: '/dashboard/super-admin',
  cr: '/dashboard/cr',
  moderator: '/dashboard/moderator',
  member: '/dashboard/member',
  // Admin
  adminNoticeBoard: '/dashboard/admin/notice-board',
  adminStudents: '/dashboard/admin/students',
  adminFeeManagement: '/dashboard/admin/fee-management',
  adminEvents: '/dashboard/admin/events',
  adminNotifications: '/dashboard/admin/notifications',
  adminAttendance: '/dashboard/admin/attendance',
  adminCertificates: '/dashboard/admin/certificates',
  adminLeaveRequests: '/dashboard/admin/leave-requests',
  adminFeedback: '/dashboard/admin/feedback',
  adminClubs: '/dashboard/admin/clubs',
  adminDocuments: '/dashboard/admin/documents',
  adminReports: '/dashboard/admin/reports',
  adminSettings: '/dashboard/admin/settings',
  // CR
  crNoticeBoard: '/dashboard/cr/notice-board',
  crEvents: '/dashboard/cr/events',
  crFeeManagement: '/dashboard/cr/fee-management',
  crStudents: '/dashboard/cr/students',
  crAttendance: '/dashboard/cr/attendance',
  crCertificates: '/dashboard/cr/certificates',
  crNotifications: '/dashboard/cr/notifications',
  crLeaveRequests: '/dashboard/cr/leave-requests',
  crFeedback: '/dashboard/cr/feedback',
  crResources: '/dashboard/cr/resources',
  crSettings: '/dashboard/cr/settings',
  // Member
  memberNotices: '/dashboard/member/notices',
  memberEvents: '/dashboard/member/events',
  memberPayments: '/dashboard/member/payments',
  memberResources: '/dashboard/member/resources',
  memberProfile: '/dashboard/member/profile',
  memberForum: '/dashboard/member/forum',
  memberClubs: '/dashboard/member/clubs',
  memberAttendance: '/dashboard/member/attendance',
  memberCertificates: '/dashboard/member/certificates',
  memberLeave: '/dashboard/member/leave',
  memberProjects: '/dashboard/member/projects',
  memberFeedback: '/dashboard/member/feedback',
  memberMentorship: '/dashboard/member/mentorship',
  memberSettings: '/dashboard/member/settings',
  // Moderator
  moderatorEvents: '/dashboard/moderator/events',
  moderatorResources: '/dashboard/moderator/resources',
  moderatorForum: '/dashboard/moderator/forum',
  moderatorNotifications: '/dashboard/moderator/notifications',
  moderatorClubs: '/dashboard/moderator/clubs',
  moderatorSettings: '/dashboard/moderator/settings',
  // Super Admin
  superAdminEvents: '/dashboard/super-admin/events',
  superAdminUsers: '/dashboard/super-admin/users',
  superAdminPayments: '/dashboard/super-admin/payments',
  superAdminLogs: '/dashboard/super-admin/logs',
  superAdminAnalytics: '/dashboard/super-admin/analytics',
  superAdminRoles: '/dashboard/super-admin/roles',
  superAdminDocuments: '/dashboard/super-admin/documents',
  superAdminNewsletter: '/dashboard/super-admin/newsletter',
  superAdminBackup: '/dashboard/super-admin/backup',
  superAdminSettings: '/dashboard/super-admin/settings',
} as const;

export const DASHBOARD_NAV = {
  admin: [
    { href: '/dashboard/admin', label: 'Dashboard', icon: 'LayoutDashboard' },
    { href: '/dashboard/admin/students', label: 'Students', icon: 'Users' },
    { href: '/dashboard/admin/fee-management', label: 'Fee Tracking', icon: 'CreditCard' },
    { href: '/dashboard/admin/events', label: 'Events', icon: 'Calendar' },
    { href: '/dashboard/admin/notice-board', label: 'Notices', icon: 'Megaphone' },
    { href: '/dashboard/admin/notifications', label: 'Notifications', icon: 'Bell' },
    { href: '/dashboard/admin/attendance', label: 'Attendance', icon: 'QrCode' },
    { href: '/dashboard/admin/certificates', label: 'Certificates', icon: 'Award' },
    { href: '/dashboard/admin/leave-requests', label: 'Leave Requests', icon: 'ClipboardList' },
    { href: '/dashboard/admin/feedback', label: 'Feedback', icon: 'MessageCircle' },
    { href: '/dashboard/admin/clubs', label: 'Clubs', icon: 'Star' },
    { href: '/dashboard/admin/documents', label: 'Documents', icon: 'FolderOpen' },
    { href: '/dashboard/admin/reports', label: 'Reports', icon: 'BarChart2' },
    { href: '/dashboard/admin/settings', label: 'Settings', icon: 'Settings' },
  ],
  superAdmin: [
    { href: '/dashboard/super-admin', label: 'Dashboard', icon: 'LayoutDashboard' },
    { href: '/dashboard/super-admin/users', label: 'Users', icon: 'Users' },
    { href: '/dashboard/super-admin/payments', label: 'Payments', icon: 'CreditCard' },
    { href: '/dashboard/super-admin/events', label: 'Events', icon: 'Calendar' },
    { href: '/dashboard/super-admin/analytics', label: 'Analytics', icon: 'BarChart2' },
    { href: '/dashboard/super-admin/roles', label: 'Role Management', icon: 'ShieldCheck' },
    { href: '/dashboard/super-admin/documents', label: 'Documents', icon: 'FolderOpen' },
    { href: '/dashboard/super-admin/newsletter', label: 'Newsletter', icon: 'Mail' },
    { href: '/dashboard/super-admin/logs', label: 'Logs', icon: 'FileText' },
    { href: '/dashboard/super-admin/backup', label: 'Backup', icon: 'Database' },
    { href: '/dashboard/super-admin/settings', label: 'Settings', icon: 'Settings' },
  ],
  cr: [
    { href: '/dashboard/cr', label: 'Dashboard', icon: 'LayoutDashboard' },
    { href: '/dashboard/cr/notice-board', label: 'Notice Board', icon: 'Megaphone' },
    { href: '/dashboard/cr/events', label: 'Events', icon: 'Calendar' },
    { href: '/dashboard/cr/fee-management', label: 'Fee Management', icon: 'CreditCard' },
    { href: '/dashboard/cr/students', label: 'Students', icon: 'Users' },
    { href: '/dashboard/cr/attendance', label: 'Attendance', icon: 'QrCode' },
    { href: '/dashboard/cr/certificates', label: 'Certificates', icon: 'Award' },
    { href: '/dashboard/cr/notifications', label: 'Notifications', icon: 'Bell' },
    { href: '/dashboard/cr/leave-requests', label: 'Leave Requests', icon: 'ClipboardList' },
    { href: '/dashboard/cr/feedback', label: 'Feedback', icon: 'MessageCircle' },
    { href: '/dashboard/cr/resources', label: 'Resources', icon: 'BookOpen' },
    { href: '/dashboard/cr/settings', label: 'Settings', icon: 'Settings' },
  ],
  moderator: [
    { href: '/dashboard/moderator', label: 'Dashboard', icon: 'LayoutDashboard' },
    { href: '/dashboard/moderator/events', label: 'Event Proposals', icon: 'Calendar' },
    { href: '/dashboard/moderator/resources', label: 'Resources', icon: 'BookOpen' },
    { href: '/dashboard/moderator/forum', label: 'Forum', icon: 'MessageSquare' },
    { href: '/dashboard/moderator/clubs', label: 'Clubs', icon: 'Star' },
    { href: '/dashboard/moderator/notifications', label: 'Notifications', icon: 'Bell' },
    { href: '/dashboard/moderator/settings', label: 'Settings', icon: 'Settings' },
  ],
  member: [
    { href: '/dashboard/member', label: 'Dashboard', icon: 'LayoutDashboard' },
    { href: '/dashboard/member/notices', label: 'Notices', icon: 'Megaphone' },
    { href: '/dashboard/member/events', label: 'Events', icon: 'Calendar' },
    { href: '/dashboard/member/forum', label: 'Forum', icon: 'MessageSquare' },
    { href: '/dashboard/member/clubs', label: 'Clubs', icon: 'Star' },
    { href: '/dashboard/member/resources', label: 'Resources', icon: 'BookOpen' },
    { href: '/dashboard/member/projects', label: 'Projects', icon: 'Layers' },
    { href: '/dashboard/member/mentorship', label: 'Mentorship', icon: 'GraduationCap' },
    { href: '/dashboard/member/attendance', label: 'Attendance', icon: 'QrCode' },
    { href: '/dashboard/member/certificates', label: 'Certificates', icon: 'Award' },
    { href: '/dashboard/member/payments', label: 'Payments', icon: 'CreditCard' },
    { href: '/dashboard/member/leave', label: 'Leave Requests', icon: 'ClipboardList' },
    { href: '/dashboard/member/feedback', label: 'Feedback', icon: 'MessageCircle' },
    { href: '/dashboard/member/profile', label: 'Profile', icon: 'User' },
  ],
} as const;
